// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:3b328d48-366c-4d4f-8a30-4c1b400a3550",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_rI4a7Lo9m",
    "aws_user_pools_web_client_id": "2kl82k9jngckrno7b0h9hgbjvb",
    "aws_mobile_analytics_app_id": "423c851c06b84d4295a1e36752a88b57",
    "aws_mobile_analytics_app_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://ckd2rd7sj5drze3amqhyjzg3yi.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-auirjbi7pba3plrdgx7m24lq7i",
    "aws_cloud_logic_custom": [
        {
            "name": "myapi",
            "endpoint": "https://uhp7wdyq97.execute-api.us-west-2.amazonaws.com/Prod",
            "region": "us-west-2"
        }
    ],
    "aws_content_delivery_bucket": "reactwebinar-20190125185451-hostingbucket",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://reactwebinar-20190125185451-hostingbucket.s3-website-us-west-2.amazonaws.com",
    "aws_dynamodb_all_tables_region": "us-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "tableforApi",
            "region": "us-west-2"
        },
        {
            "tableName": "amplifymyapi",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
